### ISSUE TITLE
它会在用一段时间之后卡住不起作用

### ISSUE THREAD

**Issue by QNsiyu** [plaidmrdeer/SkipSleep#1]
![image](https://user-images.githubusercontent.com/75734402/182882078-2505eeae-ad55-433a-a9cf-38b81e426792.png)

**Comment by QNsiyu** [comment]
1.18.1

**Comment by QNsiyu** [comment]
![image](https://user-images.githubusercontent.com/75734402/182882336-e171f208-cb62-4f11-82e4-aa4600b1350e.png)

**Comment by PlaidMrdeer** [comment]
en， 是我的疏忽 没有想到会有人尝试用字母设置 你不因该用/sks set Qn_siyu设置 这不是数字

**Comment by qqwkt** [comment]
你的意思是当Qn_Siyu睡觉的时候跳过？

**Comment by QNsiyu** [comment]
不是，而是在正常游戏时有时候会出现前一天晚上可以正常使用插件跳过晚上，而后一天就不行了。然后过了几个晚上或者不断地重设、关闭、开启和重载后又恢复过来。现在又出现了新的问题，首先是有人睡觉的进度条会卡在屏幕正上方不消失的问题，还有一个是在下雨的时候睡觉应该在起床之后雨停而使用插件后雨不停，还有就是在雷雨天气睡觉时无法正常跳过的问题。

**Comment by qqwkt** [comment]
有人睡觉的进度条会卡在屏幕正上方不消失的问题 
en我们正在努力解决。

**Comment by plaidmrdeer** [comment]
感谢您的反馈 我们将尽力修复bug

**Comment by PlaidMrdeer** [comment]
> 不是，而是在正常游戏时有时候会出现前一天晚上可以正常使用插件跳过晚上，而后一天就不行了。然后过了几个晚上或者不断地重设、关闭、开启和重载后又恢复过来。现在又出现了新的问题，首先是有人睡觉的进度条会卡在屏幕正上方不消失的问题，还有一个是在下雨的时候睡觉应该在起床之后雨停而使用插件后雨不停，还有就是在雷雨天气睡觉时无法正常跳过的问题。

感谢您的回复，我们将尽快修复bug

**Comment by PlaidMrdeer** [comment]
> 不是，而是在正常游戏时有时候会出现前一天晚上可以正常使用插件跳过晚上，而后一天就不行了。然后过了几个晚上或者不断地重设、关闭、开启和重载后又恢复过来。现在又出现了新的问题，首先是有人睡觉的进度条会卡在屏幕正上方不消失的问题，还有一个是在下雨的时候睡觉应该在起床之后雨停而使用插件后雨不停，还有就是在雷雨天气睡觉时无法正常跳过的问题。

新版本已经发布可以前往发布页下载新版了 感谢您的支持
[https://github.com/plaidmrdeer/SkipSleep/releases/tag/v1.3.1](url)
