### ISSUE TITLE
Linux下1.6.2版本依旧无法读取语言文件

### ISSUE THREAD

**Issue by sorahane0227** [plaidmrdeer/SkipSleep#2]
![D08A888B-1A24-4E07-AEA5-53E36ACF2270](https://github.com/plaidmrdeer/SkipSleep/assets/81579759/1494608d-613e-45e1-978f-02ecbd08538a)
![DD901F45-399B-48F3-AE55-C2FC484E800C](https://github.com/plaidmrdeer/SkipSleep/assets/81579759/958b6c5b-2b84-4d54-828a-19d3e6f96a47)
服务端是paperspigot 1.16.5

**Comment by PlaidMrdeer** [comment]
很抱歉 请等待更新 新版本会解决此问题
